name: Validate CloudFormation Template

on:
  push:
    paths:
      - '**.yaml'
      - '**.yml'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Validate CloudFormation templates
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          template: cloudformation/serverless_metadata_extraction.yaml
          no-fail-on-empty-changeset: true
          capabilities: CAPABILITY_NAMED_IAM
        env:
          AWS_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}